name: esp-idf-ci-action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run:
          - echo -e "\rline1\x1b[K\rline2\x1b[K\rline3\x1b[K\nEND"
          - python -c 'import sys; print(sys.stdout.isatty())'

